
return {
  diagnostics = {
    -- icons / text used for a diagnostic
    error       = " ",
    warning     = " ",
    hint        = " ",
    information = " ",
    other       = " "
  },
  diagnostics_solid = {
    error       = " ",
    warning     = " ",
    information = " ",
    other       = " ",
  },
  dap = {
    stopped     = "",
    normal      = "",
    conditional = "",
    rejected    = "ﰸ",
    log         = "",
  },
  kind = {
    Text          = "",
    Copilot       = "",
    Method        = "",
    Function      = "",
    Constructor   = "",
    Field         = "ﰠ",
    Variable      = "",
    Class         = "ﴯ",
    Interface     = "",
    Module        = "",
    Property      = "ﰠ",
    Unit          = "塞",
    Value         = "",
    Enum          = "",
    Keyword       = "",
    Snippet       = "",
    Color         = "",
    File          = "",
    Reference     = "",
    Folder        = "",
    EnumMember    = "",
    Constant      = "",
    Struct        = "פּ",
    Event         = "",
    Operator      = "",
    TypeParameter = "",
  },
  lsp = {
    buffer                   = "   BUF ",
    nvim_lsp                 = "   LSP ",
    nvim_lua                 = "   LUA ",
    path                     = " L PATH",
    luasnip                  = "   SNIP",
    treesitter               = "   TS  ",
    rg                       = "   GREP",
    cmdline                  = "   CMD ",
    dap                      = "   DAP ",
    cmp_git                  = "   GIT ",
    nvim_lsp_document_symbol = "   SYM "
  }
}
