#!/usr/bin/env bash
#
# Install Vimspector debug adapters

py_bin="/usr/bin/python3"
[[ ! -z "$1" ]] && py_bin="$1"

update_only=false
[[ ! -z "$2" && "$2" == "update" ]] && update_only=true


nvim_data_home="${XDG_DATA_HOME:-$HOME/.local/share}/nvim"
nvim_conf_home=$(dirname $( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd ))
vimspector_plugin_data="${nvim_data_home}/site/pack/packer/start/vimspector"
vimspector_basedir="${nvim_conf_home}/vimspector"

if [[ ! -d $vimspector_plugin_data ]]; then
    echo "Unable to find vimspector plugin install path: ${vimspector_plugin_data}"
    exit 1
fi

function install_gadget() {
    $py_bin "${vimspector_plugin_data}/install_gadget.py" \
        --basedir $vimspector_basedir "$@"
}

if [[ $update_only == "true" ]]; then
    install_gadget --upgrade
else
    install_gadget \
        --enable-python \
        --enable-rust \
        --enable-bash \
        --enable-lua 

    install_gadget --force-enable-node 
    install_gadget --force-enable-firefox 
fi
