#!/usr/bin/env bash
#
# Wrapper for vimspector install_gadget.py

py_bin="/usr/bin/python3"
[[ ! -z "$1" ]] && py_bin="$1"

update_only=false
[[ ! -z "$2" && "$2" == "update" ]] && update_only=true


nvim_data_home="${XDG_DATA_HOME:-$HOME/.local/share}/nvim"
nvim_conf_home=$(dirname $( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd ))
vimspector_plugin_data="${nvim_data_home}/site/pack/packer/start/vimspector"
vimspector_basedir="${nvim_conf_home}/vimspector"

if [[ ! -d $vimspector_plugin_data ]]; then
    echo "Unable to find vimspector plugin install path: ${vimspector_plugin_data}"
    exit 1
fi

python "${vimspector_plugin_data}/install_gadget.py" --basedir $vimspector_basedir "$@"

